---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

addons:
  code_climate:
    repo_token: d0c0b77e8e686f0574c52fea34c6b2d7accf687c6946c5862ad9bfd727b9e999

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version
  - npm install -g codeclimate-test-reporter


install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:each

after_script:
  - codeclimate-test-reporter < lcov.dat
